# Generated by Django 4.2.10 on 2024-04-22 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "money_collections",
            "0002_collection_created_at_collection_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="end_collection_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 29, 14, 49, 2, 949103)
            ),
        ),
    ]
